name: "Release sigstore-go"

on:
  push:
    tags:
      - "v*.*.*"

env:
  REPO: 'https://github.com/AdamKorcz/test-releasing'

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the repo _before_ issuing the release
      # so we have the ground truth.
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
      - name: Download zip source archive from API
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          zipBall: true
          out-file-path: '${{ github.workspace }}/../source-archives' # download-path
          tag: ${{ github.ref_name }}
      - name: Download tar source archive from API
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          tarBall: true
          out-file-path: '${{ github.workspace }}/../source-archives' # download-path
          tag: ${{ github.ref_name }}
      - name: Download archives from archive/tags
        working-directory: ${{ github.workspace }}
        env:
          zip_url: 'https://github.com/AdamKorcz/test-releasing/releases/tag/${{ github.ref_name }}.zip'
          tar_url: '"${REPO}"/releases/tag/${{ github.ref_name }}.tar.gz'
        run: |
          ls && pwd && ls ${{ github.workspace }}
          wget https://github.com/AdamKorcz/test-releasing/archive/tags/${{ github.ref_name }}.zip -O ${{ github.workspace }}/../source-archives/test-releasing-tags-${{ github.ref_name }}.zip
          wget https://github.com/AdamKorcz/test-releasing/archive/tags/${{ github.ref_name }}.tar.gz -O ${{ github.workspace }}/../source-archives/test-releasing-tags-${{ github.ref_name }}.tar.gz
          wget https://github.com/AdamKorcz/test-releasing/archive/refs/tags/${{ github.ref_name }}.zip -O ${{ github.workspace }}/../source-archives/test-releasing-refs-tags-${{ github.ref_name }}.zip
          wget https://github.com/AdamKorcz/test-releasing/archive/refs/tags/${{ github.ref_name }}.tar.gz -O ${{ github.workspace }}/../source-archives/test-releasing-refs-tags-${{ github.ref_name }}.tar.gz
          ls && pwd && ls ${{ github.workspace }}/../source-archives
          echo "lets unzip"
          cd ${{ github.workspace }}/../source-archives 
      - name: Verify all downloaded source archives
        working-directory: ${{ github.workspace }}
        env:
          REPO_NAME: '${{ github.event.repository.name }}'
          RELEASE_VERSION: '${{ github.ref_name }}'
        run: |
          cd ..
          ls
          export directory="test-releasing"
          if [ ! -d "$directory" ]; then
            exit 1
          fi

          verify_file() {
            filename=$1
            trusted_dir=$2
            untrusted_dir=$3
            path="${trusted_dir}/${filename#*/}"
            cs_file1=$(sha256sum "${path}" | head -c 64)

            path2="${untrusted_dir}/${filename#*/}"
            cs_file2=$(sha256sum "${path2}" | head -c 64)
            echo verifying "${path}" and "${path2}"
            if [ "$cs_file1" != "$cs_file2" ]; then exit 1; fi
          }
          export -f verify_file

          dirs_are_equal() {
            export trusted_dir=$1
            export untrusted_dir=$2 
            find $trusted_dir -type f -not -path "*.git/*" -exec bash -c 'verify_file {} $trusted_dir $untrusted_dir' \;
            number_of_files1=$(find "${trusted_dir}" -type f -not -path "*.git/*" | wc -l)
            number_of_files2=$(find "${untrusted_dir}" -type f -not -path "*.git/*" | wc -l)
            if [ "$number_of_files1" != "$number_of_files2" ]; then echo "WRONG" && exit 1; else echo "SAME AMOUNT OF FILES"; fi
            echo $number_of_files1 $number_of_files2
          }
          echo "Verifying all downloaded source archives"
          export shortened_sha=$(echo "${GITHUB_SHA}" | head -c 7)
          echo AdamKorcz-test-releasing-"${shortened_sha}"

          # verifying first zip
          export dir_name="AdamKorcz-test-releasing-${shortened_sha}"
          if [ -d "${dir_name}" ]; then
            echo "${dir_name} already exists but shouldn't."
            exit 1
          fi
          unzip source-archives/test-releasing-${{ github.ref_name }}.zip
          dirs_are_equal "${directory}" "${dir_name}"
          rm -r "${dir_name}"

          # verifying first tar gz
          export dir_name="AdamKorcz-test-releasing-${shortened_sha}"
          if [ -d "${dir_name}" ]; then
            echo "${dir_name} already exists but shouldn't."
            exit 1
          fi
          tar -xvzf source-archives/test-releasing-${{ github.ref_name }}.tar.gz
          dirs_are_equal "${directory}" "${dir_name}"
          rm -r "${dir_name}"

          # verifying second zip
          export dir_name="test-releasing-tags-${{ github.ref_name }}"
          if [ -d "${dir_name}" ]; then
            echo "${dir_name} already exists but shouldn't."
            exit 1
          fi
          unzip source-archives/test-releasing-tags-${{ github.ref_name }}.zip
          dirs_are_equal "${directory}" "${dir_name}"
          rm -r "${dir_name}"

          # verifying second tar gz
          export dir_name="test-releasing-tags-${{ github.ref_name }}"
          if [ -d "${dir_name}" ]; then
            echo "${dir_name} already exists but shouldn't."
            exit 1
          fi
          tar -xvzf source-archives/test-releasing-tags-${{ github.ref_name }}.tar.gz
          dirs_are_equal "${directory}" "${dir_name}"
          rm -r "${dir_name}"

          export TAG_WITHOUT_V=${RELEASE_VERSION#"v"} # eg. v0.0.1 becomes 0.0.1
          # verifying third zip
          export dir_name="test-releasing-${TAG_WITHOUT_V}"
          if [ -d "${dir_name}" ]; then
            echo "${dir_name} already exists but shouldn't."
            exit 1
          fi
          unzip source-archives/test-releasing-refs-tags-${{ github.ref_name }}.zip
          dirs_are_equal "${directory}" "${dir_name}"
          rm -r "${dir_name}"

          # verifying third tar gz
          export dir_name="test-releasing-${TAG_WITHOUT_V}"
          if [ -d "${dir_name}" ]; then
            echo "${dir_name} already exists but shouldn't."
            exit 1
          fi
          tar -xvzf source-archives/test-releasing-refs-tags-${{ github.ref_name }}.tar.gz
          dirs_are_equal "${directory}" "${dir_name}"
          rm -r "${dir_name}"
      - name: Move source archive files
        run: |
          mv ${{ github.workspace }}/../source-archives ./
          find source-archives -type f -exec bash -c 'echo {} && sha256sum {}' \;
      - name: Attest all
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'source-archives/*'
          




#      - name: Extract all downloaded source archives
#        working-directory: ${{ github.workspace }}
#        run: |
#          cd "${ZIP_ARCHIVES}" && unzip *.zip && cd ..
#          cd "${TAR_ARCHIVES}" && tar -xvzf *.tar.gz && cd ..
#          echo "ls" && ls
#          echo "${ZIP_ARCHIVES}" && ls "${ZIP_ARCHIVES}""
#          echo "${TAR_ARCHIVES}" && ls "${TAR_ARCHIVES}"

#      - name: 'ls downloaded'
#        run: ls -R ${{ github.workspace }}/source-files/* && unzip ${{ github.workspace }}/source-files/*.zip && ls -R ${{ github.workspace }}/source-files/* && sha256sum ${{ github.workspace }}/source-files/*.zip
#NEED THIS      - name: Attest
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ github.workspace }}/source-files/*'
#      - name: Create sigstore-go-release_tag.zip
#        env:
#          REPO_NAME: '${{ github.event.repository.name }}'
#          REPO_NAME_WITH_TAG: '${{ github.event.repository.name }}-${{ github.ref_name }}'
#          RELEASE_VERSION: '${{ github.ref_name }}'
#        run: |
#          ls ..
#          cd ..
#          # remove prefixed "v" from relase version
#          tag=${RELEASE_VERSION#"v"}
#          echo tag "${tag}"
#          mv "${REPO_NAME}" "${REPO_NAME}-${tag}"
#          ls
#          #mv ${{ github.event.repository.name }} ${{ github.event.repository.name }}-${{ github.ref_name }} 
#          zip -r "${REPO_NAME}-${tag}".zip "${REPO_NAME}-${tag}" -x "${REPO_NAME}-${tag}/.git/*"
#          sha256sum "${REPO_NAME}-${tag}".zip
#          mv "${REPO_NAME}-${tag}".zip "${REPO_NAME}-${tag}"/
#          mv "${REPO_NAME}-${tag}" "${REPO_NAME}"
#          cd "${REPO_NAME}"
#          echo "tag_zip_archive=${REPO_NAME}-${tag}.zip" >> "${GITHUB_OUTPUT}"
#          echo "${REPO_NAME}-${tag}.zip"
#          cat "${REPO_NAME}-${tag}.zip"
#        id: create_tag_zip
#      - name: Attest sigstore-go-release_tag.zip
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ steps.create_tag_zip.outputs.tag_zip_archive }}'
#      - name: Clean up sigstore-go-release_tag.zip
#        run: rm ${{ steps.create_tag_zip.outputs.tag_zip_archive }}
#      - name: Release
#        uses: softprops/action-gh-release@v2
#      - uses: robinraju/release-downloader@v1
#        with:
#          latest: true
#          tarBall: true
#          zipBall: true
#          out-file-path: 'source-files' # download-path
#          tag: ${{ github.ref_name }}
#      - name: 'ls downloaded'
#        run: ls -R ${{ github.workspace }}/source-files/* && unzip ${{ github.workspace }}/source-files/*.zip && ls -R ${{ github.workspace }}/source-files/* && sha256sum ${{ github.workspace }}/source-files/*.zip
#      - name: Attest
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ github.workspace }}/source-files/*'
          
