name: "Release sigstore-go"

on:
  push:
    tags:
      - "v*.*.*"

env:
  REPO: 'https://github.com/AdamKorcz/test-releasing'

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Check out the repo _before_ issuing the release
      # so we have the ground truth.
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
      - name: Download zip source archive from API
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          zipBall: true
          out-file-path: '${{ github.workspace }}/../source-archives' # download-path
          tag: ${{ github.ref_name }}
      - name: Download tar source archive from API
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          tarBall: true
          out-file-path: '${{ github.workspace }}/../source-archives' # download-path
          tag: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: 'downloaded-source-archives'
          path: '${{ github.workspace }}/source-archives'
      - name: Download archives from archive/tags
        working-directory: ${{ github.workspace }}
        env:
          zip_url: 'https://github.com/AdamKorcz/test-releasing/releases/tag/${{ github.ref_name }}.zip'
          tar_url: '"${REPO}"/releases/tag/${{ github.ref_name }}.tar.gz'
        run: |
          ls && pwd && ls ${{ github.workspace }}
          wget https://github.com/AdamKorcz/test-releasing/archive/tags/${{ github.ref_name }}.zip -O ${{ github.workspace }}/../source-archives/manually-downloaded.zip
          wget https://github.com/AdamKorcz/test-releasing/archive/tags/${{ github.ref_name }}.tar.gz -O ${{ github.workspace }}/../source-archives/manually-downloaded.tar.gz
          ls && pwd && ls ${{ github.workspace }}/../source-archives
      - name: Upload the downloaded source archives
        uses: actions/upload-artifact@v4
        with:
          name: source-archives
          path: ${{ github.workspace }}/../source-archives




#      - name: Extract all downloaded source archives
#        working-directory: ${{ github.workspace }}
#        run: |
#          cd "${ZIP_ARCHIVES}" && unzip *.zip && cd ..
#          cd "${TAR_ARCHIVES}" && tar -xvzf *.tar.gz && cd ..
#          echo "ls" && ls
#          echo "${ZIP_ARCHIVES}" && ls "${ZIP_ARCHIVES}""
#          echo "${TAR_ARCHIVES}" && ls "${TAR_ARCHIVES}"

#      - name: 'ls downloaded'
#        run: ls -R ${{ github.workspace }}/source-files/* && unzip ${{ github.workspace }}/source-files/*.zip && ls -R ${{ github.workspace }}/source-files/* && sha256sum ${{ github.workspace }}/source-files/*.zip
#NEED THIS      - name: Attest
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ github.workspace }}/source-files/*'
#      - name: Create sigstore-go-release_tag.zip
#        env:
#          REPO_NAME: '${{ github.event.repository.name }}'
#          REPO_NAME_WITH_TAG: '${{ github.event.repository.name }}-${{ github.ref_name }}'
#          RELEASE_VERSION: '${{ github.ref_name }}'
#        run: |
#          ls ..
#          cd ..
#          # remove prefixed "v" from relase version
#          tag=${RELEASE_VERSION#"v"}
#          echo tag "${tag}"
#          mv "${REPO_NAME}" "${REPO_NAME}-${tag}"
#          ls
#          #mv ${{ github.event.repository.name }} ${{ github.event.repository.name }}-${{ github.ref_name }} 
#          zip -r "${REPO_NAME}-${tag}".zip "${REPO_NAME}-${tag}" -x "${REPO_NAME}-${tag}/.git/*"
#          sha256sum "${REPO_NAME}-${tag}".zip
#          mv "${REPO_NAME}-${tag}".zip "${REPO_NAME}-${tag}"/
#          mv "${REPO_NAME}-${tag}" "${REPO_NAME}"
#          cd "${REPO_NAME}"
#          echo "tag_zip_archive=${REPO_NAME}-${tag}.zip" >> "${GITHUB_OUTPUT}"
#          echo "${REPO_NAME}-${tag}.zip"
#          cat "${REPO_NAME}-${tag}.zip"
#        id: create_tag_zip
#      - name: Attest sigstore-go-release_tag.zip
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ steps.create_tag_zip.outputs.tag_zip_archive }}'
#      - name: Clean up sigstore-go-release_tag.zip
#        run: rm ${{ steps.create_tag_zip.outputs.tag_zip_archive }}
#      - name: Release
#        uses: softprops/action-gh-release@v2
#      - uses: robinraju/release-downloader@v1
#        with:
#          latest: true
#          tarBall: true
#          zipBall: true
#          out-file-path: 'source-files' # download-path
#          tag: ${{ github.ref_name }}
#      - name: 'ls downloaded'
#        run: ls -R ${{ github.workspace }}/source-files/* && unzip ${{ github.workspace }}/source-files/*.zip && ls -R ${{ github.workspace }}/source-files/* && sha256sum ${{ github.workspace }}/source-files/*.zip
#      - name: Attest
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ github.workspace }}/source-files/*'
          
