name: "Release sigstore-go"

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
      - name: Create sigstore-go-release_tag.zip
        env:
          REPO_NAME: '${{ github.event.repository.name }}'
          REPO_NAME_WITH_TAG: '${{ github.event.repository.name }}-${{ github.ref_name }}'
          RELEASE_VERSION: '${{ github.ref_name }}'
        run: |
          ls ..
          cd ..
          # remove prefixed "v" from relase version
          tag=${RELEASE_VERSION#"v"}
          echo tag "${tag}"
          mv "${REPO_NAME}" "${REPO_NAME}-${tag}"
          ls
          #mv ${{ github.event.repository.name }} ${{ github.event.repository.name }}-${{ github.ref_name }} 
          zip "${REPO_NAME}-${tag}".zip "${REPO_NAME}-${tag}"
          sha256sum "${REPO_NAME}-${tag}".zip
          mv "${REPO_NAME}-${tag}".zip "${REPO_NAME}-${tag}"/
          mv "${REPO_NAME}-${tag}" "${REPO_NAME}"
          cd "${REPO_NAME}"
          echo "tag_zip_archive=${REPO_NAME}-${tag}.zip" >> "${GITHUB_OUTPUT}"
        id: create_tag_zip
      - name: Attest sigstore-go-release_tag.zip
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ steps.create_tag_zip.outputs.tag_zip_archive }}'
      - name: Clean up sigstore-go-release_tag.zip
        run: rm ${{ steps.create_tag_zip.outputs.tag_zip_archive }}
#      - name: Create sigstore-go-release_tag.tar.gz
#        env:
#          REPO_NAME: '${{ github.event.repository.name }}'
#          REPO_NAME_WITH_TAG: '${{ github.event.repository.name }}-${{ github.ref_name }}'
#        run: |
#          ls ..
#          cd ..
#          mv "${REPO_NAME}" "${REPO_NAME_WITH_TAG}"
#          tar -czvf "${REPO_NAME_WITH_TAG}/${REPO_NAME_WITH_TAG}".tar.gz "${REPO_NAME_WITH_TAG}"
#          mv "${REPO_NAME_WITH_TAG}" "${REPO_NAME}"
#          cd "${REPO_NAME}"
#      - name: Attest sigstore-go-release_tag.tar.gz
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-path: '${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz'
#      - name: Clean up sigstore-go-release_tag.zip
#        env:
#          REPO_NAME_WITH_TAG: '${{ github.event.repository.name }}-${{ github.ref_name }}'
#        run: rm "${REPO_NAME_WITH_TAG}".tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          tarBall: true
          zipBall: true
          out-file-path: 'source-files' # download-path
          tag: ${{ github.ref_name }}
      - name: 'ls downloaded'
        run: ls -R ${{ github.workspace }}/source-files/* && unzip ${{ github.workspace }}/source-files/*.zip && ls -R ${{ github.workspace }}/source-files/* && sha256sum ${{ github.workspace }}/source-files/*.zip
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/source-files/*'
