name: "Release sigstore-go"

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}
      - name: lsss
        run: |
          ls ..
          cd ..
          mv ${{ github.event.repository.name }} ${{ github.event.repository.name }}-${{ github.ref_name }} 
          zip ${{ github.event.repository.name }}-${{ github.ref_name }}/${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }}-${{ github.ref_name }}
          mv ${{ github.event.repository.name }}-${{ github.ref_name }} ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.event.repository.name }}-${{ github.ref_name }}.zip'
      - name: attest renamed zip
        run: ls && rm ${{ github.event.repository.name }}-${{ github.ref_name }}.zip && ls
      - name: Release
        uses: softprops/action-gh-release@v2
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          tarBall: true
          zipBall: true
          out-file-path: 'source-files' # download-path
          tag: ${{ github.ref_name }}
      - name: 'ls downloaded'
        run: ls -R ${{ github.workspace }}/source-files/* && unzip ${{ github.workspace }}/source-files/*.zip && ls -R ${{ github.workspace }}/source-files/* && sha256sum ${{ github.workspace }}/source-files/*.zip
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/source-files/*'
